

void main()
{
	//object oControlledChar = GetControlledCharacter(OBJECT_SELF);
	//SendMessageToPC(oControlledChar, "gui_elu_featpage executed");
	//string sRowName = GetStringByStrRef(StringToInt(Get2DAString("feat", "FEAT", 0)));
	//SendMessageToPC(oControlledChar, "rowname: " + sRowName);
	//string sTextFields = "FEAT_TEXTFIELD=" + sRowName + "XX;";
	//ModifyListBoxRow(oControlledChar, "SCREEN_CHARACTER", "FEAT_LIST", sRowName, sTextFields, "", "", "");
}